<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRX0lkk\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRX0lkk/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerKRX0lkk.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerKRX0lkk\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerKRX0lkk\App_KernelTestDebugContainer([
    'container.build_hash' => 'KRX0lkk',
    'container.build_id' => 'd4971b0b',
    'container.build_time' => 1780209749,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRX0lkk');
