<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxCvevs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxCvevs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxCvevs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxCvevs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxCvevs\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxCvevs',
    'container.build_id' => '8d0d863e',
    'container.build_time' => 1781192765,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxCvevs');
