<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWDwOlxP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWDwOlxP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWDwOlxP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWDwOlxP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWDwOlxP\App_KernelDevDebugContainer([
    'container.build_hash' => 'WDwOlxP',
    'container.build_id' => '115a9775',
    'container.build_time' => 1782174700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWDwOlxP');
