<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS7xCTjl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS7xCTjl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS7xCTjl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS7xCTjl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS7xCTjl\App_KernelDevDebugContainer([
    'container.build_hash' => 'S7xCTjl',
    'container.build_id' => 'edd3e64b',
    'container.build_time' => 1780345328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS7xCTjl');
